name: ROS 2 Jazzy CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          apt-get update
          rosdep update
          rosdep install --from-paths . --ignore-src -y --rosdistro jazzy
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_direct+
      - name: Test
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test --packages-select nav2_ready --event-handlers console_direct+
          colcon test-result --verbose
